name: your_sales
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  dio: ^5.9.0
  go_router: ^16.2.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.13
  pin_code_fields: ^8.0.1
  flutter_iconly: ^1.0.2
  flutter_spinkit: ^5.2.2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.1
  very_good_analysis: ^9.0.0
  pretty_dio_logger: ^1.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/png/
    - assets/images/svg/
 
  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
icons_launcher:
  image_path: "assets/images/png/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

# dart run icons_launcher:create
# flutter gen-l10n